### PR TITLE
fix conflict on AppConfig object update

### LINKED ISSUE #337: Another slightly different stack trace
There is a second stack trace I occassionally see that is similar to #322 but not the same:

```
[2019-10-10T19:32:07Z DEBUG scylla] loop
[2019-10-10T19:32:07Z INFO  scylla::instigator] UID: 47e18ead-a70a-4bd6-8e24-516a6809ae92
[2019-10-10T19:32:07Z INFO  scylla::instigator] Looking up example-replicable-task
[2019-10-10T19:32:07Z DEBUG scylla::trait_manager] Trait binding params: Some([ParameterValue { name: "replicaCount", value: Some(Number(3)), from_param: None }])
[2019-10-10T19:32:07Z DEBUG scylla::schematic::traits::manual_scaler] params: {"replicaCount": Number(3)}
[2019-10-10T19:32:07Z INFO  scylla::instigator] Adding component alpine-task-v1
[2019-10-10T19:32:07Z INFO  scylla::schematic::component] Looking for image pull secret
[2019-10-10T19:32:08Z INFO  scylla::instigator] Looking up example-replicable-task
[2019-10-10T19:32:08Z DEBUG scylla::instigator] Sync component alpine-task-v1, got status {"job/multi-alpine-task": "running"}
[2019-10-10T19:32:08Z DEBUG scylla::trait_manager] Trait binding params: Some([ParameterValue { name: "replicaCount", value: Some(Number(3)), from_param: None }])
[2019-10-10T19:32:08Z DEBUG scylla::schematic::traits::manual_scaler] params: {"replicaCount": Number(3)}
[2019-10-10T19:32:08Z DEBUG scylla::instigator] Patched status Some(Some(OAMStatus { phase: Some("synced"), components: Some({"alpine-task-v1": {"job/multi-alpine-task": "running"}}) })) for example-replicable-task
[2019-10-10T19:32:12Z INFO  scylla::schematic::traits::manual_scaler] Scaling example-replicable-task to 3
[2019-10-10T19:32:12Z DEBUG scylla::instigator] spec: ApplicationConfiguration { variables: None, scopes: None, components: Some([ComponentConfiguration { name: "alpine-task-v1", instance_name: "multi-alpine-task", parameter_values: Some([ParameterValue { name: "message", value: Some(String("Hello World")), from_param: None }]), traits: Some([TraitBinding { name: "manual-scaler", parameter_values: Some([ParameterValue { name: "replicaCount", value: Some(Number(3)), from_param: None }]) }]) }]) }, status: Some(Some(OAMStatus { phase: Some("Add"), components: None }))
[2019-10-10T19:32:12Z ERROR scylla] Error processing event: Error { inner: stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::hb3e9012d12460cbc (0x1022d17dd)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h7972ff562d8bedb9 (0x1022d156e)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
   2: failure::context::Context<D>::new::h48c8d2b1a9e934bb (0x10197f441)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/context.rs:84
   3: <kube::Error as core::convert::From<kube::ErrorKind>>::from::h790aa8c4d4a48df6 (0x101993d09)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.15.1/src/lib.rs:87
   4: kube::client::APIClient::request::hc9766981e3e59793 (0x1018579e6)
             at /Users/technosophos/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.15.1/src/client/mod.rs:97
   5: scylla::instigator::Instigator::exec::h3147303d23781633 (0x1017417a1)
             at /Users/technosophos/Code/Rust/scylla/src/instigator.rs:399
   6: scylla::instigator::Instigator::add::h4675d4649dedda13 (0x101741f38)
             at /Users/technosophos/Code/Rust/scylla/src/instigator.rs:408
   7: scylla::handle_event::hc4da6dc4b7ce1cae (0x1014e8340)
             at /Users/technosophos/Code/Rust/scylla/src/main.rs:177
   8: scylla::main::{{closure}}::hf69cbe0cb2604665 (0x1013c893a)
             at /Users/technosophos/Code/Rust/scylla/src/main.rs:100
   9: std::sys_common::backtrace::__rust_begin_short_backtrace::hedc380f903a73494 (0x1013577e3)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/sys_common/backtrace.rs:77
  10: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h21b0a1673a18a8ab (0x10134ef00)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/mod.rs:470
  11: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h745cdf66ab7addf1 (0x10150e513)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:315
  12: std::panicking::try::do_call::hd8c60a31a20c30bc (0x10134252f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  13: ___rust_maybe_catch_panic (0x102703eae)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libpanic_unwind/lib.rs:82
  14: std::panicking::try::h89cdf375a688c86b (0x101341ef1)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  15: std::panic::catch_unwind::h0beff9383cabdbce (0x10150e5b7)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  16: std::thread::Builder::spawn_unchecked::{{closure}}::h2936b3fd33b1539a (0x10134e78a)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/mod.rs:469
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}::h3c08964cd857c8f3 (0x10138ccb4)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha44ca87baccc45af (0x1026ec55d)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  19: std::sys::unix::thread::Thread::new::thread_start::hceb9fd3b79bf176c (0x10270341d)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  20: __pthread_body (0x7fff64e542ea)
  21: __pthread_start (0x7fff64e57248)

ApiError Conflict ("Operation cannot be fulfilled on applicationconfigurations.core.hydra.io \"example-replicable-task\": the object has been modified; please apply your changes to the latest version and try again") }
[2019-10-10T19:32:13Z INFO  scylla] Handled event
```

I saw the above when installing `examples/replicable-task.yaml` about 3 minutes after teh installation was complete

/cc @fibonacci1729

### LINKED ISSUE #344: Changes to manual-scaler in ApplicationConfiguration do not trigger change of replicas
Changing `manual-scaler` `replicaCount` from `1` to `2` does not update `deployment` replica count. The following lines are output from the `scylla` pod. This is based on the latest nightly image.
```
[2019-10-14T21:41:13Z INFO  scylla::instigator] UID: a7687b7f-eeca-11e9-8522-dca63207ff04
[2019-10-14T21:41:13Z INFO  scylla::instigator] Looking up foo-app
[2019-10-14T21:41:13Z INFO  scylla::instigator] Adding component foo-worker
[2019-10-14T21:41:13Z INFO  scylla::schematic::component] Looking for image pull secret
[2019-10-14T21:41:13Z INFO  scylla::schematic::component] found image pull secret
[2019-10-14T21:41:13Z ERROR scylla] Error processing event: Error { inner:

ApiError AlreadyExists ("deployments.apps \"foo\" already exists") }
[2019-10-14T21:41:13Z INFO  scylla] Handled event
```

### PR DESCRIPTION
**Pull request by wonderflow**
1. add patch retry incase of conflict happen. fixes #337
2. not update status when there's changes unfinshed. fixes #344
3. make cargo clippy happy

### CODE REVIEW

File: src/instigator.rs [hunk 1]
```diff
@@ -34,7 +34,7 @@ pub const COMPONENT_RECORD_ANNOTATION: &str = "component_record_annotation";
 
 /// Type alias for the results that all instantiation operations return
 pub type InstigatorResult = Result<(), Error>;
-type OpResource = Object<ApplicationConfiguration, Status>;
+type OpResource = Object<ApplicationConfiguration, OAMStatus>;
```
Comment (wonderflow) [inline src/instigator.rs]: I also use OAMStatus instead of Status here.
Because Status is a wrapper of OAMStatus with option. kube::Object will add Option wrapper for it's status generic. So if we use Status here, we will finally have `option<option< OAMStatus >>` that makes annoyance.

Comment (technosophos) [reply src/instigator.rs]: Ah! Yes, that is cleaner

File: src/instigator.rs [hunk 2]
```diff
@@ -93,12 +93,29 @@ impl Instigator {
...
+            let new_record = &ComponentRecord {
+                version: comp_def.clone().metadata.resourceVersion.unwrap(),
+                config: component.clone(),
+            };
+            let record = last_components
+                .get_mut(component.instance_name.as_str())
+                .cloned();
+            last_components.remove(component.instance_name.as_str());
+            // we can't update status when there is update not finished yet.
+            if check_diff(record.clone(), new_record) {
```
Comment (technosophos) [inline src/instigator.rs]: Good idea.

File: src/schematic/traits/volume_mounter.rs [hunk 3]
```diff
@@ -175,8 +175,8 @@ impl TraitImplementation for VolumeMounter {
             ns,
             Default::default(),
         );
-        if req.is_err() {
-            resource.insert(key, req.unwrap_err().to_string());
+        if let Err(err) = req {
```
Comment (technosophos) [inline src/schematic/traits/volume_mounter.rs]: That is much cleaner. Thanks!

File: src/schematic/traits.rs [hunk 4]
```diff
@@ -59,7 +59,7 @@ pub enum OAMTrait {
     Autoscaler(Autoscaler),
     ManualScaler(ManualScaler),
     Ingress(Ingress),
-    VolumeMounter(VolumeMounter),
+    VolumeMounter(Box<VolumeMounter>),
```
Comment (technosophos) [inline src/schematic/traits.rs]: Yay! No more linting error!

**Comment by wonderflow** [comment]
I'll merge it, you could try to use. If you find any bugs, feel free to assign issue to me.
